// <auto-generated />
using ApiLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLab.Data.Migrations
{
    [DbContext(typeof(ApiLabAppDbContext))]
    partial class ApiLabAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiLab.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Group A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Group B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Group C"
                        });
                });

            modelBuilder.Entity("ApiLab.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "ali@mail.com",
                            FullName = "Ali Həsənov",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Email = "leyla@mail.com",
                            FullName = "Leyla Əliyeva",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Email = "nicat@mail.com",
                            FullName = "Nicat Məmmədov",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            Email = "ayten@mail.com",
                            FullName = "Aytən Quliyeva",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            Email = "tural@mail.com",
                            FullName = "Tural Rəhimov",
                            GroupId = 3
                        });
                });

            modelBuilder.Entity("ApiLab.Models.Student", b =>
                {
                    b.HasOne("ApiLab.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ApiLab.Models.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
